# Site settings
name: Fabio Figueiredo
description: AI Solutions Architect | GenAI, ML, MLOps | Turning AI into Business Outcomes
baseurl: ""
url: "https://onchainlabs1.github.io"

# Social media
author:
  name: Fabio Figueiredo
  email: fabio@onchainlabs.com.br
  github: onchainlabs1
  linkedin: fabiofigueiredo1

# Use GitHub Pages supported theme
theme: minima

# Navigation
header_pages:
  - aboutme.md
  - projects.md

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock 