# Site settings
title: onchainlabs1 Portfolio
name: onchainlabs1
description: ML Engineer & Python Developer | Building AI Solutions
baseurl: ""
url: "https://onchainlabs1.github.io"

# Social media
author:
  name: onchainlabs1
  email: fabio@onchainlabs.com.br
  github: onchainlabs1
  linkedin: your-linkedin

# Use GitHub Pages supported theme
theme: minima

# Navigation
header_pages:
  - aboutme.md
  - projects.md

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock 